### Create a venue
POST http://localhost:4500/venues/create
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlY2U0YjZjZi00M2JmLTQ4NmUtOTdiNi03YWQ0ZTA0NzdjOWEiLCJ1c2VyTmFtZSI6Imtlbm55bmV0NjYiLCJlbWFpbCI6InRlc3RAdGVzdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkSmQ2SHFnTHdYVmo5dFBoRnk0OS4xdUhVNlViQ1VkbU96cFJocUduTFJFb2c1RHdpV1VNZ20iLCJpYXQiOjE3MDk5MzE5OTUsImV4cCI6MTcxMDE5MTE5NX0.T68E4YLGGVYNGJunUYfzpmaTtvOBlmPReS-DjQDGtmk

{
    "venueName": "OldTrafford",
    "venueImage": "../../../"
}

### Get all venus
GET  http://localhost:4500/venues
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlY2U0YjZjZi00M2JmLTQ4NmUtOTdiNi03YWQ0ZTA0NzdjOWEiLCJ1c2VyTmFtZSI6Imtlbm55bmV0NjYiLCJlbWFpbCI6InRlc3RAdGVzdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkSmQ2SHFnTHdYVmo5dFBoRnk0OS4xdUhVNlViQ1VkbU96cFJocUduTFJFb2c1RHdpV1VNZ20iLCJpYXQiOjE3MDk5MzE5OTUsImV4cCI6MTcxMDE5MTE5NX0.T68E4YLGGVYNGJunUYfzpmaTtvOBlmPReS-DjQDGtmk

### Get one venue
GET http://localhost:4500/venues/5620dd35-e5f5-4d08-b205-1121b2e56a4f
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlY2U0YjZjZi00M2JmLTQ4NmUtOTdiNi03YWQ0ZTA0NzdjOWEiLCJ1c2VyTmFtZSI6Imtlbm55bmV0NjYiLCJlbWFpbCI6InRlc3RAdGVzdG1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMDUkSmQ2SHFnTHdYVmo5dFBoRnk0OS4xdUhVNlViQ1VkbU96cFJocUduTFJFb2c1RHdpV1VNZ20iLCJpYXQiOjE3MDk5MzE5OTUsImV4cCI6MTcxMDE5MTE5NX0.T68E4YLGGVYNGJunUYfzpmaTtvOBlmPReS-DjQDGtmk